In [1]:
import numpy as np
import pandas as pd
import json

In [2]:
df1 = pd.read_json(r"F:\Project\access_to_elec_rural__world\API_EG.ELC.ACCS.RU.ZS_DS2_en_csv_v2_4364070.json")
df1.to_csv('df1.csv')
df1

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [35]:
df1.drop(0,axis=0,inplace=True)
df1

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [5]:
df1.columns

RangeIndex(start=0, stop=67, step=1)

In [36]:
df1.columns = df1.iloc[0]
df1

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [37]:
df1.drop(1,axis=0,inplace=True)
df1

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,NaN,
6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,,,3.81506657600403,,,7.33344507217407,,,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [38]:
df1.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
0,2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
1,3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
2,4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
3,5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,NaN,
4,6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,,,3.81506657600403,,,7.33344507217407,,,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
262,264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
263,265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
264,266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
265,267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [39]:
df1.isnull().sum()

1
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960.0            266
                 ...
2018                0
2019                0
2020                0
2021.0            266
                    0
Length: 67, dtype: int64

In [40]:
df1.dtypes

1
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960.0            float64
                   ...
2018               object
2019               object
2020               object
2021.0            float64
                   object
Length: 67, dtype: object

In [41]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          0 non-null      float64
 5   1961.0          0 non-null      float64
 6   1962.0          0 non-null      float64
 7   1963.0          0 non-null      float64
 8   1964.0          0 non-null      float64
 9   1965.0          0 non-null      float64
 10  1966.0          0 non-null      float64
 11  1967.0          0 non-null      float64
 12  1968.0          0 non-null      float64
 13  1969.0          0 non-null      float64
 14  1970.0          0 non-null      float64
 15  1971.0          0 non-null      float64
 16  1972.0          0 non-null      float64
 17  1973.0          0 non-null      float64
 18  1974.0          0 non-null      float64
 19  1975.0          0 non-null      float64
 20  1976.0          0 non-null      float64
 21  1977.0          0 non-null      float64
 22  1978.0          0 non-null      float64
 23  1979.0          0 non-null      float64
 24  1980.0          0 non-null      float64
 25  1981.0          0 non-null      float64
 26  1982.0          0 non-null      float64
 27  1983.0          0 non-null      float64
 28  1984.0          0 non-null      float64
 29  1985.0          0 non-null      float64
 30  1986.0          0 non-null      float64
 31  1987.0          0 non-null      float64
 32  1988.0          0 non-null      float64
 33  1989.0          0 non-null      float64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          0 non-null      float64
 66                  266 non-null    object
dtypes: float64(31), object(36)
memory usage: 139.4+ KB

In [42]:
df1.fillna(0, inplace = True)
df1

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0.0,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0.0,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0.0,
6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,,,3.81506657600403,,,7.33344507217407,,,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,0.0,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,0.0,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,0.0,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,0.0,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,0.0,

In [43]:
df1['Indicator Name']=df1['Indicator Name'].str.replace(',','')
df1.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0.0,
4,Afghanistan,AFG,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0.0,
5,Africa Western and Central,AFW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0.0,
6,Angola,AGO,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,,,3.81506657600403,,,7.33344507217407,,,0.0,

In [44]:
df1.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0.0,
4,Afghanistan,AFG,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0.0,
5,Africa Western and Central,AFW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0.0,
6,Angola,AGO,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,,,3.81506657600403,,,7.33344507217407,,,0.0,

In [45]:
df1.dtypes

1
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960.0            float64
                   ...
2018               object
2019               object
2020               object
2021.0            float64
                   object
Length: 67, dtype: object

In [46]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          266 non-null    float64
 5   1961.0          266 non-null    float64
 6   1962.0          266 non-null    float64
 7   1963.0          266 non-null    float64
 8   1964.0          266 non-null    float64
 9   1965.0          266 non-null    float64
 10  1966.0          266 non-null    float64
 11  1967.0          266 non-null    float64
 12  1968.0          266 non-null    float64
 13  1969.0          266 non-null    float64
 14  1970.0          266 non-null    float64
 15  1971.0          266 non-null    float64
 16  1972.0          266 non-null    float64
 17  1973.0          266 non-null    float64
 18  1974.0          266 non-null    float64
 19  1975.0          266 non-null    float64
 20  1976.0          266 non-null    float64
 21  1977.0          266 non-null    float64
 22  1978.0          266 non-null    float64
 23  1979.0          266 non-null    float64
 24  1980.0          266 non-null    float64
 25  1981.0          266 non-null    float64
 26  1982.0          266 non-null    float64
 27  1983.0          266 non-null    float64
 28  1984.0          266 non-null    float64
 29  1985.0          266 non-null    float64
 30  1986.0          266 non-null    float64
 31  1987.0          266 non-null    float64
 32  1988.0          266 non-null    float64
 33  1989.0          266 non-null    float64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          266 non-null    float64
 66                  266 non-null    object
dtypes: float64(31), object(36)
memory usage: 139.4+ KB

In [47]:
### converting the Float datatypes to Int datatypes for easy calculation

df1[1960.0]=df1[1960.0].astype("int64")
df1[1961.0]=df1[1961.0].astype("int64")
df1[1962.0]=df1[1962.0].astype("int64")
df1[1963.0]=df1[1963.0].astype("int64")
df1[1964.0]=df1[1964.0].astype("int64")
df1[1965.0]=df1[1965.0].astype("int64")
df1[1966.0]=df1[1966.0].astype("int64")
df1[1967.0]=df1[1967.0].astype("int64")
df1[1968.0]=df1[1968.0].astype("int64")
df1[1969.0]=df1[1969.0].astype("int64")
df1[1970.0]=df1[1970.0].astype("int64")
df1[1971.0]=df1[1971.0].astype("int64")
df1[1972.0]=df1[1972.0].astype("int64")
df1[1973.0]=df1[1973.0].astype("int64")
df1[1974.0]=df1[1974.0].astype("int64")
df1[1975.0]=df1[1975.0].astype("int64")
df1[1976.0]=df1[1976.0].astype("int64")
df1[1977.0]=df1[1977.0].astype("int64")
df1[1978.0]=df1[1978.0].astype("int64")
df1[1979.0]=df1[1979.0].astype("int64")
df1[1980.0]=df1[1980.0].astype("int64")
df1[1981.0]=df1[1981.0].astype("int64")
df1[1982.0]=df1[1982.0].astype("int64")
df1[1983.0]=df1[1983.0].astype("int64")
df1[1984.0]=df1[1984.0].astype("int64")
df1[1985.0]=df1[1985.0].astype("int64")
df1[1986.0]=df1[1986.0].astype("int64")
df1[1987.0]=df1[1987.0].astype("int64")
df1[1988.0]=df1[1988.0].astype("int64")
df1[1989.0]=df1[1989.0].astype("int64")
df1[2021.0]=df1[2021.0].astype("int64")
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          266 non-null    int64
 5   1961.0          266 non-null    int64
 6   1962.0          266 non-null    int64
 7   1963.0          266 non-null    int64
 8   1964.0          266 non-null    int64
 9   1965.0          266 non-null    int64
 10  1966.0          266 non-null    int64
 11  1967.0          266 non-null    int64
 12  1968.0          266 non-null    int64
 13  1969.0          266 non-null    int64
 14  1970.0          266 non-null    int64
 15  1971.0          266 non-null    int64
 16  1972.0          266 non-null    int64
 17  1973.0          266 non-null    int64
 18  1974.0          266 non-null    int64
 19  1975.0          266 non-null    int64
 20  1976.0          266 non-null    int64
 21  1977.0          266 non-null    int64
 22  1978.0          266 non-null    int64
 23  1979.0          266 non-null    int64
 24  1980.0          266 non-null    int64
 25  1981.0          266 non-null    int64
 26  1982.0          266 non-null    int64
 27  1983.0          266 non-null    int64
 28  1984.0          266 non-null    int64
 29  1985.0          266 non-null    int64
 30  1986.0          266 non-null    int64
 31  1987.0          266 non-null    int64
 32  1988.0          266 non-null    int64
 33  1989.0          266 non-null    int64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          266 non-null    int64
 66                  266 non-null    object
dtypes: int64(31), object(36)
memory usage: 139.4+ KB

In [48]:
df1.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0,
4,Afghanistan,AFG,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0,
5,Africa Western and Central,AFW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0,
6,Angola,AGO,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,,,3.81506657600403,,,7.33344507217407,,,0,

In [49]:
for x in df1.columns[4:66]:
    df1.rename({str(x):'_'+str(x)}, axis=1, inplace = True)
df1.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,2021.0,
2,Aruba,ABW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0,
4,Afghanistan,AFG,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0,
5,Africa Western and Central,AFW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0,
6,Angola,AGO,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,,,3.81506657600403,,,7.33344507217407,,,0,

In [50]:
### Creating a dictionary for renaming the multiple columns
dic ={}
for x in df1.columns[4:66]:
    dic[x]=str(x)
df1.rename(columns=dic, inplace= True)
df1

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,2021.0,
2,Aruba,ABW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0,
4,Afghanistan,AFG,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0,
5,Africa Western and Central,AFW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0,
6,Angola,AGO,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,,,3.81506657600403,,,7.33344507217407,,,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,0,
264,"Yemen, Rep.",YEM,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,0,
265,South Africa,ZAF,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,0,
266,Zambia,ZMB,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,0,
267,Zimbabwe,ZWE,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,0,

In [51]:
df1.rename({1960.0:'_1960',1961.0:'_1961',1962.0:'_1962',1963.0:'_1963',1964.0:'_1964',2021.0:'_2021'},axis=1,inplace=True)
df1

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,2021.0,
2,Aruba,ABW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0,
4,Afghanistan,AFG,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0,
5,Africa Western and Central,AFW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0,
6,Angola,AGO,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,,,3.81506657600403,,,7.33344507217407,,,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,0,
264,"Yemen, Rep.",YEM,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,0,
265,South Africa,ZAF,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,0,
266,Zambia,ZMB,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,0,
267,Zimbabwe,ZWE,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,0,

In [52]:
df1.columns[1]

'Country Code'

In [53]:
df1.ffill(axis=1)

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,2021.0,
2,Aruba,ABW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0,
4,Afghanistan,AFG,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0,
5,Africa Western and Central,AFW,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0,
6,Angola,AGO,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,,,3.81506657600403,,,7.33344507217407,,,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,0,
264,"Yemen, Rep.",YEM,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,0,
265,South Africa,ZAF,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,0,
266,Zambia,ZMB,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,0,
267,Zimbabwe,ZWE,Access to electricity rural (% of rural popula...,EG.ELC.ACCS.RU.ZS,0,0,0,0,0,0,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,0,

In [54]:
df1.to_csv(r"F:\Project\access_to_elec_rural__world\elec_rural.csv", header = True, index= False)

In [ ]:
###-------------------------------
###-------------------------------
###-------------------------------

In [14]:
df2 = pd.read_json(r"F:\Project\access_to_electricity__total\API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_4353549.json")
df2.to_csv('df2.csv')
df2

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [15]:
df2.drop(0,axis=0,inplace = True)
df2

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [17]:
df2.columns = df2.iloc[0]
df2

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [18]:
df2.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
0,1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
1,2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
2,3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
3,4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
4,5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
263,264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
264,265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
265,266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
266,267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [19]:
df2.drop(1,axis=0,inplace=True)
df2

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [20]:
df2.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
0,2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
1,3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
2,4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
3,5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
4,6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
262,264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
263,265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
264,266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
265,267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [21]:
df2.fillna(0,inplace = True)
df2

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,0.0,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,0.0,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,0.0,
6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,0.0,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,0.0,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,0.0,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,0.0,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,0.0,

In [22]:
df2.dtypes

1
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960.0            float64
                   ...
2018               object
2019               object
2020               object
2021.0            float64
                   object
Length: 67, dtype: object

In [23]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          266 non-null    float64
 5   1961.0          266 non-null    float64
 6   1962.0          266 non-null    float64
 7   1963.0          266 non-null    float64
 8   1964.0          266 non-null    float64
 9   1965.0          266 non-null    float64
 10  1966.0          266 non-null    float64
 11  1967.0          266 non-null    float64
 12  1968.0          266 non-null    float64
 13  1969.0          266 non-null    float64
 14  1970.0          266 non-null    float64
 15  1971.0          266 non-null    float64
 16  1972.0          266 non-null    float64
 17  1973.0          266 non-null    float64
 18  1974.0          266 non-null    float64
 19  1975.0          266 non-null    float64
 20  1976.0          266 non-null    float64
 21  1977.0          266 non-null    float64
 22  1978.0          266 non-null    float64
 23  1979.0          266 non-null    float64
 24  1980.0          266 non-null    float64
 25  1981.0          266 non-null    float64
 26  1982.0          266 non-null    float64
 27  1983.0          266 non-null    float64
 28  1984.0          266 non-null    float64
 29  1985.0          266 non-null    float64
 30  1986.0          266 non-null    float64
 31  1987.0          266 non-null    float64
 32  1988.0          266 non-null    float64
 33  1989.0          266 non-null    float64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          266 non-null    float64
 66                  266 non-null    object
dtypes: float64(31), object(36)
memory usage: 139.4+ KB

In [24]:
df2[1960.0]=df2[1960.0].astype("int64")
df2[1961.0]=df2[1961.0].astype("int64")
df2[1962.0]=df2[1962.0].astype("int64")
df2[1963.0]=df2[1963.0].astype("int64")
df2[1964.0]=df2[1964.0].astype("int64")
df2[1965.0]=df2[1965.0].astype("int64")
df2[1966.0]=df2[1966.0].astype("int64")
df2[1967.0]=df2[1967.0].astype("int64")
df2[1968.0]=df2[1968.0].astype("int64")
df2[1969.0]=df2[1969.0].astype("int64")
df2[1970.0]=df2[1970.0].astype("int64")
df2[1971.0]=df2[1971.0].astype("int64")
df2[1972.0]=df2[1972.0].astype("int64")
df2[1973.0]=df2[1973.0].astype("int64")
df2[1974.0]=df2[1974.0].astype("int64")
df2[1975.0]=df2[1975.0].astype("int64")
df2[1976.0]=df2[1976.0].astype("int64")
df2[1977.0]=df2[1977.0].astype("int64")
df2[1978.0]=df2[1978.0].astype("int64")
df2[1979.0]=df2[1979.0].astype("int64")
df2[1980.0]=df2[1980.0].astype("int64")
df2[1981.0]=df2[1981.0].astype("int64")
df2[1982.0]=df2[1982.0].astype("int64")
df2[1983.0]=df2[1983.0].astype("int64")
df2[1984.0]=df2[1984.0].astype("int64")
df2[1985.0]=df2[1985.0].astype("int64")
df2[1986.0]=df2[1986.0].astype("int64")
df2[1987.0]=df2[1987.0].astype("int64")
df2[1988.0]=df2[1988.0].astype("int64")
df2[1989.0]=df2[1989.0].astype("int64")
df2[2021.0]=df2[2021.0].astype("int64")
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          266 non-null    int64
 5   1961.0          266 non-null    int64
 6   1962.0          266 non-null    int64
 7   1963.0          266 non-null    int64
 8   1964.0          266 non-null    int64
 9   1965.0          266 non-null    int64
 10  1966.0          266 non-null    int64
 11  1967.0          266 non-null    int64
 12  1968.0          266 non-null    int64
 13  1969.0          266 non-null    int64
 14  1970.0          266 non-null    int64
 15  1971.0          266 non-null    int64
 16  1972.0          266 non-null    int64
 17  1973.0          266 non-null    int64
 18  1974.0          266 non-null    int64
 19  1975.0          266 non-null    int64
 20  1976.0          266 non-null    int64
 21  1977.0          266 non-null    int64
 22  1978.0          266 non-null    int64
 23  1979.0          266 non-null    int64
 24  1980.0          266 non-null    int64
 25  1981.0          266 non-null    int64
 26  1982.0          266 non-null    int64
 27  1983.0          266 non-null    int64
 28  1984.0          266 non-null    int64
 29  1985.0          266 non-null    int64
 30  1986.0          266 non-null    int64
 31  1987.0          266 non-null    int64
 32  1988.0          266 non-null    int64
 33  1989.0          266 non-null    int64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          266 non-null    int64
 66                  266 non-null    object
dtypes: int64(31), object(36)
memory usage: 139.4+ KB

In [26]:
for x in df2.columns[4:67]:
    df2.rename({str(x):'_'+str(x)},axis=1,inplace = True)
df2.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,2021.0,_
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,0,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,0,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,0,
6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,0,

In [27]:
df2.rename({1960.0:'_1960',1961.0:'_1961',1962.0:'_1962',1963.0:'_1963',1964.0:'_1964',2021.0:'_2021'},axis=1,inplace=True)
df2

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,_2021,_
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,0,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,0,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,0,
6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,0,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,0,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,0,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,0,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,0,0,0,0,0,0,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,0,

In [28]:
df2.to_csv(r"F:\Project\access_to_electricity__total\electricity__total.csv",header = True, index= False)

In [ ]:
#####
#####
#####

In [3]:
df3 = pd.read_json(r"F:\Project\access_to_electricity_urban__world\API_EG.ELC.ACCS.UR.ZS_DS2_en_csv_v2_4367536.json")
df3

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [4]:
df3.to_csv('df3.csv')
df3

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [5]:
df3.drop(0,axis=0,inplace = True)
df3

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [6]:
df3.columns = df3.iloc[0]
df3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [7]:
df3.drop(1,axis=0,inplace = True)
df3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,NaN,
6,Angola,AGO,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [8]:
df3.reset_index()
df3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,NaN,
6,Angola,AGO,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [9]:
df3.isnull().sum()

1
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960.0            266
                 ...
2018                0
2019                0
2020                0
2021.0            266
                    0
Length: 67, dtype: int64

In [10]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          0 non-null      float64
 5   1961.0          0 non-null      float64
 6   1962.0          0 non-null      float64
 7   1963.0          0 non-null      float64
 8   1964.0          0 non-null      float64
 9   1965.0          0 non-null      float64
 10  1966.0          0 non-null      float64
 11  1967.0          0 non-null      float64
 12  1968.0          0 non-null      float64
 13  1969.0          0 non-null      float64
 14  1970.0          0 non-null      float64
 15  1971.0          0 non-null      float64
 16  1972.0          0 non-null      float64
 17  1973.0          0 non-null      float64
 18  1974.0          0 non-null      float64
 19  1975.0          0 non-null      float64
 20  1976.0          0 non-null      float64
 21  1977.0          0 non-null      float64
 22  1978.0          0 non-null      float64
 23  1979.0          0 non-null      float64
 24  1980.0          0 non-null      float64
 25  1981.0          0 non-null      float64
 26  1982.0          0 non-null      float64
 27  1983.0          0 non-null      float64
 28  1984.0          0 non-null      float64
 29  1985.0          0 non-null      float64
 30  1986.0          0 non-null      float64
 31  1987.0          0 non-null      float64
 32  1988.0          0 non-null      float64
 33  1989.0          0 non-null      float64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          0 non-null      float64
 66                  266 non-null    object
dtypes: float64(31), object(36)
memory usage: 139.4+ KB

In [11]:
df3.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,NaN,
6,Angola,AGO,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,NaN,

In [12]:
df3['Indicator Name']=df3['Indicator Name'].str.replace(',','')
df3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
5,Africa Western and Central,AFW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,NaN,
6,Angola,AGO,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [13]:
df3.fillna(0,inplace= True)
df3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,0.0,
4,Afghanistan,AFG,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,0.0,
5,Africa Western and Central,AFW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,0.0,
6,Angola,AGO,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,0.0,
264,"Yemen, Rep.",YEM,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,0.0,
265,South Africa,ZAF,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,0.0,
266,Zambia,ZMB,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,0.0,
267,Zimbabwe,ZWE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,0.0,

In [14]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          266 non-null    float64
 5   1961.0          266 non-null    float64
 6   1962.0          266 non-null    float64
 7   1963.0          266 non-null    float64
 8   1964.0          266 non-null    float64
 9   1965.0          266 non-null    float64
 10  1966.0          266 non-null    float64
 11  1967.0          266 non-null    float64
 12  1968.0          266 non-null    float64
 13  1969.0          266 non-null    float64
 14  1970.0          266 non-null    float64
 15  1971.0          266 non-null    float64
 16  1972.0          266 non-null    float64
 17  1973.0          266 non-null    float64
 18  1974.0          266 non-null    float64
 19  1975.0          266 non-null    float64
 20  1976.0          266 non-null    float64
 21  1977.0          266 non-null    float64
 22  1978.0          266 non-null    float64
 23  1979.0          266 non-null    float64
 24  1980.0          266 non-null    float64
 25  1981.0          266 non-null    float64
 26  1982.0          266 non-null    float64
 27  1983.0          266 non-null    float64
 28  1984.0          266 non-null    float64
 29  1985.0          266 non-null    float64
 30  1986.0          266 non-null    float64
 31  1987.0          266 non-null    float64
 32  1988.0          266 non-null    float64
 33  1989.0          266 non-null    float64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          266 non-null    float64
 66                  266 non-null    object
dtypes: float64(31), object(36)
memory usage: 139.4+ KB

In [15]:
df3[1960.0]=df3[1960.0].astype("int64")
df3[1961.0]=df3[1961.0].astype("int64")
df3[1962.0]=df3[1962.0].astype("int64")
df3[1963.0]=df3[1963.0].astype("int64")
df3[1964.0]=df3[1964.0].astype("int64")
df3[1965.0]=df3[1965.0].astype("int64")
df3[1966.0]=df3[1966.0].astype("int64")
df3[1967.0]=df3[1967.0].astype("int64")
df3[1968.0]=df3[1968.0].astype("int64")
df3[1969.0]=df3[1969.0].astype("int64")
df3[1970.0]=df3[1970.0].astype("int64")
df3[1971.0]=df3[1971.0].astype("int64")
df3[1972.0]=df3[1972.0].astype("int64")
df3[1973.0]=df3[1973.0].astype("int64")
df3[1974.0]=df3[1974.0].astype("int64")
df3[1975.0]=df3[1975.0].astype("int64")
df3[1976.0]=df3[1976.0].astype("int64")
df3[1977.0]=df3[1977.0].astype("int64")
df3[1978.0]=df3[1978.0].astype("int64")
df3[1979.0]=df3[1979.0].astype("int64")
df3[1980.0]=df3[1980.0].astype("int64")
df3[1981.0]=df3[1981.0].astype("int64")
df3[1982.0]=df3[1982.0].astype("int64")
df3[1983.0]=df3[1983.0].astype("int64")
df3[1984.0]=df3[1984.0].astype("int64")
df3[1985.0]=df3[1985.0].astype("int64")
df3[1986.0]=df3[1986.0].astype("int64")
df3[1987.0]=df3[1987.0].astype("int64")
df3[1988.0]=df3[1988.0].astype("int64")
df3[1989.0]=df3[1989.0].astype("int64")
df3[2021.0]=df3[2021.0].astype("int64")
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          266 non-null    int64
 5   1961.0          266 non-null    int64
 6   1962.0          266 non-null    int64
 7   1963.0          266 non-null    int64
 8   1964.0          266 non-null    int64
 9   1965.0          266 non-null    int64
 10  1966.0          266 non-null    int64
 11  1967.0          266 non-null    int64
 12  1968.0          266 non-null    int64
 13  1969.0          266 non-null    int64
 14  1970.0          266 non-null    int64
 15  1971.0          266 non-null    int64
 16  1972.0          266 non-null    int64
 17  1973.0          266 non-null    int64
 18  1974.0          266 non-null    int64
 19  1975.0          266 non-null    int64
 20  1976.0          266 non-null    int64
 21  1977.0          266 non-null    int64
 22  1978.0          266 non-null    int64
 23  1979.0          266 non-null    int64
 24  1980.0          266 non-null    int64
 25  1981.0          266 non-null    int64
 26  1982.0          266 non-null    int64
 27  1983.0          266 non-null    int64
 28  1984.0          266 non-null    int64
 29  1985.0          266 non-null    int64
 30  1986.0          266 non-null    int64
 31  1987.0          266 non-null    int64
 32  1988.0          266 non-null    int64
 33  1989.0          266 non-null    int64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          266 non-null    int64
 66                  266 non-null    object
dtypes: int64(31), object(36)
memory usage: 139.4+ KB

In [16]:
for x in df3.columns[4:]:
    df3.rename({str(x):'_'+str(x)},axis=1,inplace = True)
df3.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,2021.0,_
2,Aruba,ABW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,0,
4,Afghanistan,AFG,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,0,
5,Africa Western and Central,AFW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,0,
6,Angola,AGO,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,0,

In [17]:
dic = {}
for i in df3.columns[4:]:
    dic[i] = str(i)
    
df3.rename(columns = dic, inplace = True)
df3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,2021.0,_
2,Aruba,ABW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,0,
4,Afghanistan,AFG,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,0,
5,Africa Western and Central,AFW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,0,
6,Angola,AGO,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,0,
264,"Yemen, Rep.",YEM,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,0,
265,South Africa,ZAF,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,0,
266,Zambia,ZMB,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,0,
267,Zimbabwe,ZWE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,0,

In [18]:
df3.rename({1960.0:'_1960',1961.0:'_1961',1962.0:'_1962',1963.0:'_1963',1964.0:'_1964',2021.0:'_2021'},axis=1,inplace=True)
df3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,2021.0,_
2,Aruba,ABW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,0,
4,Afghanistan,AFG,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,0,
5,Africa Western and Central,AFW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,0,
6,Angola,AGO,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,0,
264,"Yemen, Rep.",YEM,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,0,
265,South Africa,ZAF,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,0,
266,Zambia,ZMB,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,0,
267,Zimbabwe,ZWE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,0,

In [19]:
df3.dtypes

1
Country Name      object
Country Code      object
Indicator Name    object
Indicator Code    object
1960.0             int64
                   ...
_2018             object
_2019             object
_2020             object
2021.0             int64
_                 object
Length: 67, dtype: object

In [20]:
df3.ffill(axis=1)

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,2021.0,_
2,Aruba,ABW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,100,100,100,100,100,100,100,100,0,
3,Africa Eastern and Southern,AFE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,0,
4,Afghanistan,AFG,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,0,
5,Africa Western and Central,AFW,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,0,
6,Angola,AGO,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,0,
264,"Yemen, Rep.",YEM,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,0,
265,South Africa,ZAF,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,0,
266,Zambia,ZMB,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,0,
267,Zimbabwe,ZWE,Access to electricity urban (% of urban popula...,EG.ELC.ACCS.UR.ZS,0,0,0,0,0,0,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,0,

In [21]:
df3.to_csv(r"F:\Project\access_to_electricity_urban__world\electricity_urban__world.csv",header = True, index = False)

In [ ]:
######-------------------------
######-------------------------
######-------------------------

In [23]:
df4 = pd.read_json(r"F:\Project\electricity_power_transmissoin_distribution_losses\API_EG.ELC.LOSS.ZS_DS2_en_csv_v2_4357259.json")
df4

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [24]:
df4.to_csv('df4.csv')
df4

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [25]:
df4.drop(0,axis= 0,inplace = True)
df4

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [26]:
df4.columns=df4.iloc[0]
df4

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [27]:
df4.drop(1,axis=0,inplace = True)
df4

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [28]:
df4.reset_index()
df4

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [29]:
df4.info()
df4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            266 non-null    object
 5   1961            266 non-null    object
 6   1962            266 non-null    object
 7   1963            266 non-null    object
 8   1964            266 non-null    object
 9   1965            266 non-null    object
 10  1966            266 non-null    object
 11  1967            266 non-null    object
 12  1968            266 non-null    object
 13  1969            266 non-null    object
 14  1970            266 non-null    object
 15  1971            266 non-null    object
 16  1972            266 non-null    object
 17  1973            266 non-null    object
 18  1974            266 non-null    object
 19  1975            266 non-null    object
 20  1976            266 non-null    object
 21  1977            266 non-null    object
 22  1978            266 non-null    object
 23  1979            266 non-null    object
 24  1980            266 non-null    object
 25  1981            266 non-null    object
 26  1982            266 non-null    object
 27  1983            266 non-null    object
 28  1984            266 non-null    object
 29  1985            266 non-null    object
 30  1986            266 non-null    object
 31  1987            266 non-null    object
 32  1988            266 non-null    object
 33  1989            266 non-null    object
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015.0          0 non-null      float64
 60  2016.0          0 non-null      float64
 61  2017.0          0 non-null      float64
 62  2018.0          0 non-null      float64
 63  2019.0          0 non-null      float64
 64  2020.0          0 non-null      float64
 65  2021.0          0 non-null      float64
 66                  266 non-null    object
dtypes: float64(7), object(60)
memory usage: 139.4+ KB

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [30]:
df4.isnull().sum()

1
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960                0
                 ...
2018.0            266
2019.0            266
2020.0            266
2021.0            266
                    0
Length: 67, dtype: int64

In [32]:
df4.fillna(0,inplace= True)
df4

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,0.0,0.0,0.0,0.0,0.0,0.0,0.0,

In [33]:
df4['Indicator Name']=df4['Indicator Name'].str.replace(',','')
df4

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,0.0,0.0,0.0,0.0,0.0,0.0,0.0,

In [34]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            266 non-null    object
 5   1961            266 non-null    object
 6   1962            266 non-null    object
 7   1963            266 non-null    object
 8   1964            266 non-null    object
 9   1965            266 non-null    object
 10  1966            266 non-null    object
 11  1967            266 non-null    object
 12  1968            266 non-null    object
 13  1969            266 non-null    object
 14  1970            266 non-null    object
 15  1971            266 non-null    object
 16  1972            266 non-null    object
 17  1973            266 non-null    object
 18  1974            266 non-null    object
 19  1975            266 non-null    object
 20  1976            266 non-null    object
 21  1977            266 non-null    object
 22  1978            266 non-null    object
 23  1979            266 non-null    object
 24  1980            266 non-null    object
 25  1981            266 non-null    object
 26  1982            266 non-null    object
 27  1983            266 non-null    object
 28  1984            266 non-null    object
 29  1985            266 non-null    object
 30  1986            266 non-null    object
 31  1987            266 non-null    object
 32  1988            266 non-null    object
 33  1989            266 non-null    object
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015.0          266 non-null    float64
 60  2016.0          266 non-null    float64
 61  2017.0          266 non-null    float64
 62  2018.0          266 non-null    float64
 63  2019.0          266 non-null    float64
 64  2020.0          266 non-null    float64
 65  2021.0          266 non-null    float64
 66                  266 non-null    object
dtypes: float64(7), object(60)
memory usage: 139.4+ KB

In [36]:
df4[2015.0]=df4[2015.0].astype("object")
df4[2016.0]=df4[2016.0].astype("object")
df4[2017.0]=df4[2017.0].astype("object")
df4[2018.0]=df4[2018.0].astype("object")
df4[2019.0]=df4[2019.0].astype("object")
df4[2020.0]=df4[2020.0].astype("object")
df4[2021.0]=df4[2021.0].astype("object")
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            266 non-null    object
 5   1961            266 non-null    object
 6   1962            266 non-null    object
 7   1963            266 non-null    object
 8   1964            266 non-null    object
 9   1965            266 non-null    object
 10  1966            266 non-null    object
 11  1967            266 non-null    object
 12  1968            266 non-null    object
 13  1969            266 non-null    object
 14  1970            266 non-null    object
 15  1971            266 non-null    object
 16  1972            266 non-null    object
 17  1973            266 non-null    object
 18  1974            266 non-null    object
 19  1975            266 non-null    object
 20  1976            266 non-null    object
 21  1977            266 non-null    object
 22  1978            266 non-null    object
 23  1979            266 non-null    object
 24  1980            266 non-null    object
 25  1981            266 non-null    object
 26  1982            266 non-null    object
 27  1983            266 non-null    object
 28  1984            266 non-null    object
 29  1985            266 non-null    object
 30  1986            266 non-null    object
 31  1987            266 non-null    object
 32  1988            266 non-null    object
 33  1989            266 non-null    object
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015.0          266 non-null    object
 60  2016.0          266 non-null    object
 61  2017.0          266 non-null    object
 62  2018.0          266 non-null    object
 63  2019.0          266 non-null    object
 64  2020.0          266 non-null    object
 65  2021.0          266 non-null    object
 66                  266 non-null    object
dtypes: object(67)
memory usage: 139.4+ KB

In [37]:
for x in df4.columns[4:66]:
    df4.rename({str(x):'_'+str(x)}, axis=1, inplace=True)
df4.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,

In [39]:
dic = {}
for x in df4.columns[4:67]:
    dic[x] = str(x)
df4.rename(columns = dic, inplace = True)
df4

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,0.0,0.0,0.0,0.0,0.0,0.0,0.0,

In [40]:
df4.rename({1960.0:'_1960',1961.0:'_1961',1962.0:'_1962',1963.0:'_1963',1964.0:'_1964',2021.0:'_2021'},axis=1,inplace=True)
df4

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,0.0,0.0,0.0,0.0,0.0,0.0,0.0,

In [42]:
for i,j in enumerate(df4.columns[60:]):
     df4[j] = df4[df4.columns[56+i:60+i]].mean(axis=1)
df4

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18976\3190335315.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df4[j] = df4[df4.columns[56+i:60+i]].mean(axis=1)

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [43]:
df4.to_csv(r"F:\Project\electricity_power_transmissoin_distribution_losses\transmissoin_distribution.csv",header = True, index = False)

In [ ]:
###----------------
###----------------
###----------------

In [4]:
df5 = pd.read_json(r"F:\Project\electricity_production_nuclear_sources\API_EG.ELC.NUCL.ZS_DS2_en_csv_v2_4357319.json")
df5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [5]:
df5.to_csv('df5.csv')
df5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [6]:
df5.drop(0,axis=0,inplace = True)
df5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [7]:
df5.columns= df5.iloc[0]
df5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [8]:
df5.drop(1,axis= 0, inplace = True)
df5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [29]:
df5.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
0,2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df5.dtypes

1
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
_1960              object
                   ...
2018.0            float64
2019.0            float64
2020.0            float64
2021.0            float64
_                 float64
Length: 67, dtype: object

In [31]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   _1960           266 non-null    object
 5   _1961           266 non-null    object
 6   _1962           266 non-null    object
 7   _1963           266 non-null    object
 8   _1964           266 non-null    object
 9   _1965           266 non-null    object
 10  _1966           266 non-null    object
 11  _1967           266 non-null    object
 12  _1968           266 non-null    object
 13  _1969           266 non-null    object
 14  _1970           266 non-null    object
 15  _1971           266 non-null    object
 16  _1972           266 non-null    object
 17  _1973           266 non-null    object
 18  _1974           266 non-null    object
 19  _1975           266 non-null    object
 20  _1976           266 non-null    object
 21  _1977           266 non-null    object
 22  _1978           266 non-null    object
 23  _1979           266 non-null    object
 24  _1980           266 non-null    object
 25  _1981           266 non-null    object
 26  _1982           266 non-null    object
 27  _1983           266 non-null    object
 28  _1984           266 non-null    object
 29  _1985           266 non-null    object
 30  _1986           266 non-null    object
 31  _1987           266 non-null    object
 32  _1988           266 non-null    object
 33  _1989           266 non-null    object
 34  _1990           266 non-null    object
 35  _1991           266 non-null    object
 36  _1992           266 non-null    object
 37  _1993           266 non-null    object
 38  _1994           266 non-null    object
 39  _1995           266 non-null    object
 40  _1996           266 non-null    object
 41  _1997           266 non-null    object
 42  _1998           266 non-null    object
 43  _1999           266 non-null    object
 44  _2000           266 non-null    object
 45  _2001           266 non-null    object
 46  _2002           266 non-null    object
 47  _2003           266 non-null    object
 48  _2004           266 non-null    object
 49  _2005           266 non-null    object
 50  _2006           266 non-null    object
 51  _2007           266 non-null    object
 52  _2008           266 non-null    object
 53  _2009           266 non-null    object
 54  _2010           266 non-null    object
 55  _2011           266 non-null    object
 56  _2012           266 non-null    object
 57  _2013           266 non-null    object
 58  _2014           266 non-null    object
 59  _2015           266 non-null    object
 60  2016.0          0 non-null      float64
 61  2017.0          0 non-null      float64
 62  2018.0          0 non-null      float64
 63  2019.0          0 non-null      float64
 64  2020.0          0 non-null      float64
 65  2021.0          0 non-null      float64
 66  _               0 non-null      float64
dtypes: float64(7), object(60)
memory usage: 139.4+ KB

In [32]:
df5.isnull().sum()

1
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
_1960               0
                 ...
2018.0            266
2019.0            266
2020.0            266
2021.0            266
_                 266
Length: 67, dtype: int64

In [33]:
df5.fillna(0,inplace = True)
df5

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
df5['Indicator Name']= df5['Indicator Name'].str.replace(',','')
df5

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   _1960           266 non-null    object
 5   _1961           266 non-null    object
 6   _1962           266 non-null    object
 7   _1963           266 non-null    object
 8   _1964           266 non-null    object
 9   _1965           266 non-null    object
 10  _1966           266 non-null    object
 11  _1967           266 non-null    object
 12  _1968           266 non-null    object
 13  _1969           266 non-null    object
 14  _1970           266 non-null    object
 15  _1971           266 non-null    object
 16  _1972           266 non-null    object
 17  _1973           266 non-null    object
 18  _1974           266 non-null    object
 19  _1975           266 non-null    object
 20  _1976           266 non-null    object
 21  _1977           266 non-null    object
 22  _1978           266 non-null    object
 23  _1979           266 non-null    object
 24  _1980           266 non-null    object
 25  _1981           266 non-null    object
 26  _1982           266 non-null    object
 27  _1983           266 non-null    object
 28  _1984           266 non-null    object
 29  _1985           266 non-null    object
 30  _1986           266 non-null    object
 31  _1987           266 non-null    object
 32  _1988           266 non-null    object
 33  _1989           266 non-null    object
 34  _1990           266 non-null    object
 35  _1991           266 non-null    object
 36  _1992           266 non-null    object
 37  _1993           266 non-null    object
 38  _1994           266 non-null    object
 39  _1995           266 non-null    object
 40  _1996           266 non-null    object
 41  _1997           266 non-null    object
 42  _1998           266 non-null    object
 43  _1999           266 non-null    object
 44  _2000           266 non-null    object
 45  _2001           266 non-null    object
 46  _2002           266 non-null    object
 47  _2003           266 non-null    object
 48  _2004           266 non-null    object
 49  _2005           266 non-null    object
 50  _2006           266 non-null    object
 51  _2007           266 non-null    object
 52  _2008           266 non-null    object
 53  _2009           266 non-null    object
 54  _2010           266 non-null    object
 55  _2011           266 non-null    object
 56  _2012           266 non-null    object
 57  _2013           266 non-null    object
 58  _2014           266 non-null    object
 59  _2015           266 non-null    object
 60  2016.0          266 non-null    float64
 61  2017.0          266 non-null    float64
 62  2018.0          266 non-null    float64
 63  2019.0          266 non-null    float64
 64  2020.0          266 non-null    float64
 65  2021.0          266 non-null    float64
 66  _               266 non-null    float64
dtypes: float64(7), object(60)
memory usage: 139.4+ KB

In [ ]:
for x in df5.columns[4:]:
    
    df5.rename({str(x):'_'+str(x)}, axis=1, inplace=True)
df5.head()

In [ ]:
dic = {}
for x in df5.columns[4:]:
    dic[x] = str(x)
    
df5.rename(columns = dic, inplace = True)
df5

In [ ]:
df5.rename({1960.0:'_1960',1961.0:'_1961',1962.0:'_1962',1963.0:'_1963',1964.0:'_1964',2021.0:'_2021'},axis=1,inplace=True)
df5

In [ ]:
for x,y in enumerate(df5.columns[60:]):
     df5[y] = df5[df5.columns[56+x:60+x]].mean(axis=1)
df5

In [ ]:
df5.ffill(axis=1)

In [ ]:
df5.to_csv(r"F:\Project\electricity_production_nuclear_sources\production_nuclear.csv",header = True, index = False)

In [ ]:
###-------
###-------
###-------

In [39]:
df6= pd.read_json(r"F:\Project\electricity_production_oil_sources\API_EG.ELC.PETR.ZS_DS2_en_csv_v2_4356435.json")
df6.to_csv('df6.csv')
df6

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [40]:
df6.drop(0,axis= 0,inplace = True)
df6

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [41]:
df6.columns= df6.iloc[0]
df6

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [42]:
df6.drop(1,axis= 0,inplace =True)
df6

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [43]:
df6.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
0,2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
2,4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
4,6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
262,264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
263,265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
264,266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
265,267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [44]:
df6.dtypes

1
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960               object
                   ...
2018.0            float64
2019.0            float64
2020.0            float64
2021.0            float64
                   object
Length: 67, dtype: object

In [45]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            266 non-null    object
 5   1961            266 non-null    object
 6   1962            266 non-null    object
 7   1963            266 non-null    object
 8   1964            266 non-null    object
 9   1965            266 non-null    object
 10  1966            266 non-null    object
 11  1967            266 non-null    object
 12  1968            266 non-null    object
 13  1969            266 non-null    object
 14  1970            266 non-null    object
 15  1971            266 non-null    object
 16  1972            266 non-null    object
 17  1973            266 non-null    object
 18  1974            266 non-null    object
 19  1975            266 non-null    object
 20  1976            266 non-null    object
 21  1977            266 non-null    object
 22  1978            266 non-null    object
 23  1979            266 non-null    object
 24  1980            266 non-null    object
 25  1981            266 non-null    object
 26  1982            266 non-null    object
 27  1983            266 non-null    object
 28  1984            266 non-null    object
 29  1985            266 non-null    object
 30  1986            266 non-null    object
 31  1987            266 non-null    object
 32  1988            266 non-null    object
 33  1989            266 non-null    object
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016.0          0 non-null      float64
 61  2017.0          0 non-null      float64
 62  2018.0          0 non-null      float64
 63  2019.0          0 non-null      float64
 64  2020.0          0 non-null      float64
 65  2021.0          0 non-null      float64
 66                  266 non-null    object
dtypes: float64(6), object(61)
memory usage: 139.4+ KB

In [46]:
df6.isnull().sum()

1
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960                0
                 ...
2018.0            266
2019.0            266
2020.0            266
2021.0            266
                    0
Length: 67, dtype: int64

In [48]:
df6.fillna(0,inplace = True)
df6

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,0.0,0.0,0.0,0.0,0.0,0.0,

In [55]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   _1960           266 non-null    object
 5   _1961           266 non-null    object
 6   _1962           266 non-null    object
 7   _1963           266 non-null    object
 8   _1964           266 non-null    object
 9   _1965           266 non-null    object
 10  _1966           266 non-null    object
 11  _1967           266 non-null    object
 12  _1968           266 non-null    object
 13  _1969           266 non-null    object
 14  _1970           266 non-null    object
 15  _1971           266 non-null    object
 16  _1972           266 non-null    object
 17  _1973           266 non-null    object
 18  _1974           266 non-null    object
 19  _1975           266 non-null    object
 20  _1976           266 non-null    object
 21  _1977           266 non-null    object
 22  _1978           266 non-null    object
 23  _1979           266 non-null    object
 24  _1980           266 non-null    object
 25  _1981           266 non-null    object
 26  _1982           266 non-null    object
 27  _1983           266 non-null    object
 28  _1984           266 non-null    object
 29  _1985           266 non-null    object
 30  _1986           266 non-null    object
 31  _1987           266 non-null    object
 32  _1988           266 non-null    object
 33  _1989           266 non-null    object
 34  _1990           266 non-null    object
 35  _1991           266 non-null    object
 36  _1992           266 non-null    object
 37  _1993           266 non-null    object
 38  _1994           266 non-null    object
 39  _1995           266 non-null    object
 40  _1996           266 non-null    object
 41  _1997           266 non-null    object
 42  _1998           266 non-null    object
 43  _1999           266 non-null    object
 44  _2000           266 non-null    object
 45  _2001           266 non-null    object
 46  _2002           266 non-null    object
 47  _2003           266 non-null    object
 48  _2004           266 non-null    object
 49  _2005           266 non-null    object
 50  _2006           266 non-null    object
 51  _2007           266 non-null    object
 52  _2008           266 non-null    object
 53  _2009           266 non-null    object
 54  _2010           266 non-null    object
 55  _2011           266 non-null    object
 56  _2012           266 non-null    object
 57  _2013           266 non-null    object
 58  _2014           266 non-null    object
 59  _2015           266 non-null    object
 60  2016.0          0 non-null      float64
 61  2017.0          0 non-null      float64
 62  2018.0          0 non-null      float64
 63  2019.0          0 non-null      float64
 64  2020.0          0 non-null      float64
 65  2021.0          0 non-null      float64
 66  _               0 non-null      float64
dtypes: float64(7), object(60)
memory usage: 139.4+ KB

In [49]:
df6['Indicator Name']= df6['Indicator Name'].str.replace(',','')
df6

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,0.0,0.0,0.0,0.0,0.0,0.0,

In [50]:
for x in df6.columns[4:]:
    
    df6.rename({str(x):'_'+str(x)}, axis=1, inplace=True)
df6.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,0.0,0.0,0.0,0.0,0.0,0.0,

In [51]:
dic = {}
for x in df6.columns[4:]:
    dic[x] = str(x)
    
df6.rename(columns = dic, inplace = True)
df6

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,0.0,0.0,0.0,0.0,0.0,0.0,

In [52]:
df6.rename({1960.0:'_1960',1961.0:'_1961',1962.0:'_1962',1963.0:'_1963',1964.0:'_1964',2021.0:'_2021'},axis=1,inplace=True)
df6

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,0.0,0.0,0.0,0.0,0.0,0.0,

In [53]:
for x,y in enumerate(df6.columns[60:]):
     df6[y] = df6[df6.columns[56+x:60+x]].mean(axis=1)
df6

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1388\4123473767.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df6[y] = df6[df6.columns[56+x:60+x]].mean(axis=1)

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df6.ffill(axis= 1)

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,,,,,,,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,3.33076647467845,3.33076647467845,3.33076647467845,3.33076647467845,3.33076647467845,3.33076647467845,3.33076647467845
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,,,,,,,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,7.82024821265885,7.82024821265885,7.82024821265885,7.82024821265885,7.82024821265885,7.82024821265885,7.82024821265885
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,46.8250716919295,46.8250716919295,46.8250716919295,46.8250716919295,46.8250716919295,46.8250716919295,46.8250716919295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,0.245138094459879,0.245138094459879,0.245138094459879,0.245138094459879,0.245138094459879,0.245138094459879,0.245138094459879
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,60.1952684941795,60.1952684941795,60.1952684941795,60.1952684941795,60.1952684941795,60.1952684941795,60.1952684941795
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,0.074168341871474,0.074168341871474,0.074168341871474,0.074168341871474,0.074168341871474,0.074168341871474,0.074168341871474
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,3.00617605476598,3.00617605476598,3.00617605476598,3.00617605476598,3.00617605476598,3.00617605476598,3.00617605476598
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,0.494386651560408,0.494386651560408,0.494386651560408,0.494386651560408,0.494386651560408,0.494386651560408,0.494386651560408