In [1]:
import numpy as np
import pandas as pd
import json

In [2]:
df5 = pd.read_json(r"F:\Project\electricity_production_nuclear_sources\API_EG.ELC.NUCL.ZS_DS2_en_csv_v2_4357319.json")
df5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [3]:
df5.to_csv('df5.csv')
df5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [4]:
df5.drop(0,axis=0,inplace = True)
df5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [5]:
df5.columns= df5.iloc[0]
df5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [6]:
df5.drop(1,axis= 0, inplace = True)
df5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [7]:
df5.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
0,2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
2,4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
4,6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
262,264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
263,265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
264,266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [8]:
df5.dtypes

1
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960               object
                   ...
2018.0            float64
2019.0            float64
2020.0            float64
2021.0            float64
                   object
Length: 67, dtype: object

In [9]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            266 non-null    object
 5   1961            266 non-null    object
 6   1962            266 non-null    object
 7   1963            266 non-null    object
 8   1964            266 non-null    object
 9   1965            266 non-null    object
 10  1966            266 non-null    object
 11  1967            266 non-null    object
 12  1968            266 non-null    object
 13  1969            266 non-null    object
 14  1970            266 non-null    object
 15  1971            266 non-null    object
 16  1972            266 non-null    object
 17  1973            266 non-null    object
 18  1974            266 non-null    object
 19  1975            266 non-null    object
 20  1976            266 non-null    object
 21  1977            266 non-null    object
 22  1978            266 non-null    object
 23  1979            266 non-null    object
 24  1980            266 non-null    object
 25  1981            266 non-null    object
 26  1982            266 non-null    object
 27  1983            266 non-null    object
 28  1984            266 non-null    object
 29  1985            266 non-null    object
 30  1986            266 non-null    object
 31  1987            266 non-null    object
 32  1988            266 non-null    object
 33  1989            266 non-null    object
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016.0          0 non-null      float64
 61  2017.0          0 non-null      float64
 62  2018.0          0 non-null      float64
 63  2019.0          0 non-null      float64
 64  2020.0          0 non-null      float64
 65  2021.0          0 non-null      float64
 66                  266 non-null    object
dtypes: float64(6), object(61)
memory usage: 139.4+ KB

In [10]:
df5.isnull().sum()

1
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960                0
                 ...
2018.0            266
2019.0            266
2020.0            266
2021.0            266
                    0
Length: 67, dtype: int64

In [11]:
df5.fillna(0,inplace = True)
df5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,

In [12]:
df5[2016.0]=df5[2016.0].astype("object")
df5[2017.0]=df5[2017.0].astype("object")
df5[2018.0]=df5[2018.0].astype("object")
df5[2019.0]=df5[2019.0].astype("object")
df5[2020.0]=df5[2020.0].astype("object")
df5[2021.0]=df5[2021.0].astype("object")
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            266 non-null    object
 5   1961            266 non-null    object
 6   1962            266 non-null    object
 7   1963            266 non-null    object
 8   1964            266 non-null    object
 9   1965            266 non-null    object
 10  1966            266 non-null    object
 11  1967            266 non-null    object
 12  1968            266 non-null    object
 13  1969            266 non-null    object
 14  1970            266 non-null    object
 15  1971            266 non-null    object
 16  1972            266 non-null    object
 17  1973            266 non-null    object
 18  1974            266 non-null    object
 19  1975            266 non-null    object
 20  1976            266 non-null    object
 21  1977            266 non-null    object
 22  1978            266 non-null    object
 23  1979            266 non-null    object
 24  1980            266 non-null    object
 25  1981            266 non-null    object
 26  1982            266 non-null    object
 27  1983            266 non-null    object
 28  1984            266 non-null    object
 29  1985            266 non-null    object
 30  1986            266 non-null    object
 31  1987            266 non-null    object
 32  1988            266 non-null    object
 33  1989            266 non-null    object
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016.0          266 non-null    object
 61  2017.0          266 non-null    object
 62  2018.0          266 non-null    object
 63  2019.0          266 non-null    object
 64  2020.0          266 non-null    object
 65  2021.0          266 non-null    object
 66                  266 non-null    object
dtypes: object(67)
memory usage: 139.4+ KB

In [13]:
df5['Indicator Name']= df5['Indicator Name'].str.replace(',','')
df5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,

In [14]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            266 non-null    object
 5   1961            266 non-null    object
 6   1962            266 non-null    object
 7   1963            266 non-null    object
 8   1964            266 non-null    object
 9   1965            266 non-null    object
 10  1966            266 non-null    object
 11  1967            266 non-null    object
 12  1968            266 non-null    object
 13  1969            266 non-null    object
 14  1970            266 non-null    object
 15  1971            266 non-null    object
 16  1972            266 non-null    object
 17  1973            266 non-null    object
 18  1974            266 non-null    object
 19  1975            266 non-null    object
 20  1976            266 non-null    object
 21  1977            266 non-null    object
 22  1978            266 non-null    object
 23  1979            266 non-null    object
 24  1980            266 non-null    object
 25  1981            266 non-null    object
 26  1982            266 non-null    object
 27  1983            266 non-null    object
 28  1984            266 non-null    object
 29  1985            266 non-null    object
 30  1986            266 non-null    object
 31  1987            266 non-null    object
 32  1988            266 non-null    object
 33  1989            266 non-null    object
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016.0          266 non-null    object
 61  2017.0          266 non-null    object
 62  2018.0          266 non-null    object
 63  2019.0          266 non-null    object
 64  2020.0          266 non-null    object
 65  2021.0          266 non-null    object
 66                  266 non-null    object
dtypes: object(67)
memory usage: 139.4+ KB

In [15]:
for x in df5.columns[4:]:
    
    df5.rename({str(x):'_'+str(x)}, axis=1, inplace=True)
df5.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,

In [16]:
dic = {}
for x in df5.columns[4:]:
    dic[x] = str(x)
    
df5.rename(columns = dic, inplace = True)
df5

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,

In [17]:
df5.rename({1960.0:'_1960',1961.0:'_1961',1962.0:'_1962',1963.0:'_1963',1964.0:'_1964',2021.0:'_2021'},axis=1,inplace=True)
df5

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,

In [18]:
for x,y in enumerate(df5.columns[60:]):
     df5[y] = df5[df5.columns[56+x:60+x]].mean(axis=1)
df5

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16868\3412102272.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df5[y] = df5[df5.columns[56+x:60+x]].mean(axis=1)

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df5.ffill(axis=1)

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,,,,,,,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,,,,,,,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,,,,,,,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,,,,,,,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,,,,,,,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,,,,,,,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,,,,,,,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,,,,,,,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,,,,,,,

In [20]:
df5.to_csv(r"F:\Project\electricity_production_nuclear_sources\production_nuclear.csv",header = True, index = False)